spring:
  application:
    name: order-serivce
  datasource:
    url: jdbc:mysql://localhost:3306/fiverr_order
    username: root
    password: 8129057270
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8083