server:
  port: 8081
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/fiver_auth
    username: root
    password: 8129057270
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 6337216492-6hnpen9vgmo0bq1d8thoidvm4a3nj2jr.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code.google
            scope:
              - openid
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect